name: Deploy site (build react/vite to GitHub Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'react/vite/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: react/vite/package-lock.json

      # Gunakan "npm install" agar tidak gagal karena lockfile lama
      - name: Install deps (react/vite)
        working-directory: react/vite
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Build (react/vite)
        working-directory: react/vite
        run: npm run build

      - name: Prepare _site (gabungkan repo + dist ke /react/vite)
        run: |
          mkdir -p _site
          rsync -a --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude 'react/vite/node_modules' \
            --exclude 'react/vite/dist' \
            ./ _site/
          rsync -a --delete react/vite/dist/ _site/react/vite/
          touch _site/.nojekyll
          echo "== list _site/react/vite ==" && ls -la _site/react/vite
          echo "== list _site/react/vite/assets ==" && ls -la _site/react/vite/assets || true

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
